[package]
name = "eda-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "2.0"
rand = "0.8"
image = "0.24"
imageproc = "0.23"
log = "0.4"
rstar = "0.12"
env_logger = "0.11"
rayon = "1.8"
dashmap = "5.5"
